// 英文會話句子（美式）。格式：[英文, 中文, 發音提示（可省略）]
// 發音提示寫台灣人最常念錯的地方，例如 th、r／l、v、字尾子音、連音。
// slot 跟日文一樣：morning 09:00、noon 11:30、evening 20:00 的推播用哪些場景。

export const SCENES_EN = [
  {
    id: 'greet', icon: '💬', name: '寒暄', slot: 'morning',
    phrases: [
      ['Good morning!', '早安！'],
      ['Hi, how are you?', '嗨，你好嗎？'],
      ["I'm good, thanks. And you?", '我很好，謝謝。你呢？'],
      ['Thank you so much.', '非常感謝。', 'th 要把舌尖輕咬在上下牙齒中間'],
      ['Excuse me.', '不好意思／請問一下。'],
      ["I'm sorry.", '對不起。'],
      ['Nice to meet you.', '很高興認識你。', 'meet you 連在一起念「米丘」'],
      ["I'm from Taiwan.", '我從台灣來的。'],
      ['Could you say that again?', '可以再說一次嗎？', 'that 的 th 要咬舌'],
      ['Could you speak more slowly, please?', '可以說慢一點嗎？'],
      ["I don't understand.", '我聽不懂。'],
      ['How do you say this in English?', '這個英文怎麼說？', 'this 的 th 要咬舌'],
      ['Have a nice day!', '祝你有美好的一天！', 'have 的 v 要咬下唇'],
      ['See you later.', '待會見。'],
      ['Goodbye.', '再見。'],
    ],
  },
  {
    id: 'airport', icon: '✈️', name: '機場', slot: 'morning',
    phrases: [
      ["Here's my passport.", '這是我的護照。'],
      ["I'm here for sightseeing.", '我來觀光的。'],
      ["I'm staying for five days.", '我會停留五天。', 'five 的 v 要咬下唇，days 字尾有 z 的聲音'],
      ["I'm staying at the Hilton Hotel.", '我住在希爾頓飯店。'],
      ["I have nothing to declare.", '我沒有要申報的東西。', 'nothing 的 th 要咬舌'],
      ['Can I have a window seat?', '可以給我靠窗的座位嗎？'],
      ['Can I have an aisle seat?', '可以給我靠走道的座位嗎？', 'aisle 的 s 不發音，念「愛偶」'],
      ["I'd like to check this bag.", '我想托運這個行李。'],
      ['Where is gate twelve?', '12 號登機門在哪裡？'],
      ["My baggage didn't come out.", '我的行李沒有出來。'],
      ['Where can I exchange money?', '哪裡可以換錢？'],
      ['Where is the bus to downtown?', '往市區的巴士在哪裡？'],
    ],
  },
  {
    id: 'transport', icon: '🚃', name: '交通', slot: 'morning',
    phrases: [
      ['Where is the subway station?', '地鐵站在哪裡？'],
      ['How do I get to Times Square?', '要怎麼去時代廣場？'],
      ['Does this train go to Central Park?', '這班車有到中央公園嗎？'],
      ['Where can I buy a ticket?', '在哪裡買票？'],
      ['Which platform is it?', '是哪一個月台？'],
      ['Where do I transfer?', '要在哪裡轉車？'],
      ["What's the next stop?", '下一站是哪裡？'],
      ["I'd like to get off here.", '我要在這裡下車。', 'get off 連在一起念「給拉夫」'],
      ['Please take me to this address.', '請載我到這個地址。'],
      ['How long does it take?', '要多久？'],
      ['Can I walk there?', '走路到得了嗎？'],
      ["I'm lost.", '我迷路了。', 'lost 字尾的 st 要念出來'],
      ['Is it on the left or the right?', '在左邊還是右邊？', 'left 的 l 和 right 的 r 要分清楚'],
      ['Could you show me on the map?', '可以在地圖上指給我看嗎？'],
    ],
  },
  {
    id: 'food', icon: '🍔', name: '餐廳', slot: 'noon',
    phrases: [
      ['A table for two, please.', '兩位，謝謝。'],
      ["We don't have a reservation.", '我們沒有訂位。'],
      ['Can I see the menu, please?', '可以給我看菜單嗎？'],
      ['What do you recommend?', '你推薦什麼？'],
      ["I'll have this one.", '我要這個。'],
      ["I'll have the same.", '我也要一樣的。'],
      ['Could I get some water, please?', '可以給我一些水嗎？', 'water 美式念「華德」'],
      ['Not too spicy, please.', '請不要太辣。'],
      ["I'm allergic to peanuts.", '我對花生過敏。'],
      ['For here, please.', '內用。'],
      ['To go, please.', '外帶。'],
      ['This is delicious!', '這個很好吃！', 'this 的 th 要咬舌'],
      ['Can I have the check, please?', '可以結帳嗎？'],
      ['Can I pay by card?', '可以刷卡嗎？'],
      ['Can we split the bill?', '我們可以分開付嗎？'],
      ['Keep the change.', '不用找了。'],
    ],
  },
  {
    id: 'cafe', icon: '☕', name: '咖啡店', slot: 'noon',
    phrases: [
      ["Can I get a medium latte?", '可以給我一杯中杯拿鐵嗎？'],
      ['Hot, please.', '熱的，謝謝。'],
      ['Iced, please.', '冰的，謝謝。'],
      ['Less ice, please.', '少冰，謝謝。', 'less 的 l 要把舌尖頂在上牙後面'],
      ['No sugar, please.', '不要加糖。'],
      ['Can I get oat milk instead?', '可以換成燕麥奶嗎？'],
      ["What's your name?", '（店員會問）你叫什麼名字？'],
      ["That's all, thanks.", '就這樣，謝謝。', "that's 的 th 要咬舌"],
      ['Do you have Wi-Fi?', '有 Wi-Fi 嗎？'],
      ["What's the Wi-Fi password?", 'Wi-Fi 密碼是什麼？'],
      ['Where is the restroom?', '洗手間在哪裡？', 'restroom 的 r 要捲舌'],
      ['Can I sit here?', '我可以坐這裡嗎？', 'sit 是短音，不要念成 seat'],
    ],
  },
  {
    id: 'shop', icon: '🛍️', name: '購物', slot: 'noon',
    phrases: [
      ['How much is this?', '這個多少錢？', 'this 的 th 要咬舌'],
      ["I'm just looking, thanks.", '我只是看看，謝謝。'],
      ['Can I try this on?', '我可以試穿嗎？', 'try this on 連在一起念'],
      ['Do you have a larger size?', '有大一點的尺寸嗎？'],
      ['Do you have a smaller size?', '有小一點的尺寸嗎？'],
      ['Do you have this in black?', '這個有黑色的嗎？'],
      ["I'll take it.", '我要買這個。'],
      ['Is this on sale?', '這個有特價嗎？'],
      ['Can I get a tax refund?', '可以退稅嗎？'],
      ['Can I get a bag, please?', '可以給我一個袋子嗎？', 'bag 字尾的 g 要念出來，不要念成 back'],
      ['Could you gift wrap it?', '可以幫我包裝成禮物嗎？'],
      ['Can I get a receipt?', '可以給我收據嗎？', 'receipt 的 p 不發音'],
      ['Can I return this?', '這個可以退貨嗎？'],
      ["I'm paying in cash.", '我付現金。'],
    ],
  },
  {
    id: 'hotel', icon: '🏨', name: '飯店', slot: 'evening',
    phrases: [
      ["I'd like to check in, please.", '我要辦理入住。'],
      ['I have a reservation under Wang.', '我用王的名字訂了房。'],
      ['What time is check-out?', '幾點退房？'],
      ['What time is breakfast?', '早餐是幾點？'],
      ['Could you keep my luggage?', '可以幫我寄放行李嗎？'],
      ["What's the Wi-Fi password?", 'Wi-Fi 密碼是什麼？'],
      ['I lost my room key.', '我把房間鑰匙弄丟了。'],
      ["There's no hot water.", '沒有熱水。'],
      ["The air conditioner doesn't work.", '冷氣壞了。'],
      ['Could I get another towel?', '可以再給我一條毛巾嗎？'],
      ['Is there a convenience store nearby?', '附近有便利商店嗎？'],
      ['Could you call a taxi for me?', '可以幫我叫計程車嗎？'],
      ["I'd like to stay one more night.", '我想多住一晚。', 'night 字尾的 t 要輕輕念出來'],
    ],
  },
  {
    id: 'sight', icon: '🗽', name: '觀光', slot: 'evening',
    phrases: [
      ['Could you take a picture for us?', '可以幫我們拍張照嗎？'],
      ['Can I take pictures here?', '這裡可以拍照嗎？'],
      ['How much is the ticket?', '門票多少錢？'],
      ['Two adults, please.', '兩張成人票。'],
      ['What time do you close?', '你們幾點關門？', 'close 字尾是 z 的聲音'],
      ['Where is the entrance?', '入口在哪裡？'],
      ['Where is the exit?', '出口在哪裡？'],
      ['Are there any lockers?', '有置物櫃嗎？', 'lockers 的 l 不要念成 r'],
      ['Is there a guided tour?', '有導覽行程嗎？'],
      ['What do you recommend seeing?', '你推薦去看什麼？'],
      ['Is it far from here?', '離這裡遠嗎？', 'far 的 f 要咬下唇'],
      ['This view is amazing!', '這個景色太棒了！', 'view 的 v 要咬下唇'],
    ],
  },
  {
    id: 'pharmacy', icon: '💊', name: '看病', slot: 'evening',
    phrases: [
      ['Where is the nearest pharmacy?', '最近的藥局在哪裡？'],
      ['I have a headache.', '我頭痛。'],
      ['I have a stomachache.', '我肚子痛。', 'stomach 的 ch 念 k'],
      ['I have a fever.', '我發燒了。', 'fever 的 v 要咬下唇'],
      ['I have a cold.', '我感冒了。'],
      ['I have a sore throat.', '我喉嚨痛。', 'throat 的 th 要咬舌'],
      ['Do you have something for a cold?', '有治感冒的藥嗎？'],
      ['I feel sick.', '我覺得不舒服。', 'sick 是短音'],
      ['How many times a day should I take it?', '一天要吃幾次？'],
      ["I'm allergic to penicillin.", '我對盤尼西林過敏。'],
      ['I need to see a doctor.', '我需要看醫生。'],
      ['Can I get a band-aid?', '可以給我 OK 繃嗎？'],
    ],
  },
  {
    id: 'emergency', icon: '🆘', name: '緊急', slot: 'evening',
    phrases: [
      ['Help!', '救命！'],
      ['Please call an ambulance!', '請叫救護車！'],
      ['Please call the police!', '請叫警察！'],
      ["I'm hurt.", '我受傷了。'],
      ['I lost my wallet.', '我的錢包不見了。'],
      ['I lost my passport.', '我的護照不見了。'],
      ['My phone was stolen.', '我的手機被偷了。'],
      ['Where is the police station?', '警察局在哪裡？'],
      ['Does anyone speak Chinese?', '有人會說中文嗎？'],
      ['I need to contact the Taiwan office.', '我需要聯絡台灣辦事處。'],
      ["It's an emergency!", '這是緊急狀況！'],
      ['Where is the hospital?', '醫院在哪裡？'],
    ],
  },
];
